version: '3.4'

x-qwc-service-variables: &qwc-service-variables
  JWT_SECRET_KEY: $JWT_SECRET_KEY
  JWT_COOKIE_CSRF_PROTECT: 'True'
  # Set these to override the UID/GID which runs uwsgi. Useful to ensure uwsgi runs under the same user/group
  # which owns the shared volumes on host, avoiding the need to change the ownership/permissions of those files/folders.
  #SERVICE_UID: ${UID}
  #SERVICE_GID: ${GID}
  PGSERVICEFILE: "/srv/pg_services/pg_service.conf"
  TENANT_URL_RE: '^https?://(.+?)[-|.]'
  #TENANT_URL_RE: ^https?://.+?/(.+?)/
  POST_PARAM_LOGIN: True

services:
  qwc-qgis-server:
    image: sourcepole/qwc-qgis-server:3.22-plugins
    environment:
      <<: *qwc-service-variables
      #QGIS_SERVER_LOG_LEVEL: DEBUG
      #QGIS_SERVER_LOG_PROFILE: true
    volumes:
      - /app/qwc2/qgs-resources:/data:ro
      - /app/qwc2/pg_services:/etc/postgresql-common:ro
      - /app/qgis-server/auth-db:/qgs-server-auth-db
      - /app/qgis-server/conf:/etc/apache2/sites-enabled
      - /etc/localtime:/etc/localtime:ro

  qwc-config-service:
    image: sourcepole/qwc-config-generator:v2022.08.22
    # Lightweight variant without qgis, use if you don't need the split_categorized_layers feature
    # image: sourcepole/qwc-config-generator:v2022.08.22-noqgis
    environment:
      <<: *qwc-service-variables
      INPUT_CONFIG_PATH: '/srv/qwc_service/config-in'
      OUTPUT_CONFIG_PATH: '/srv/qwc_service/config-out'
      GENERATE_DYNAMIC_KVRELS: 1
    volumes:
      - /app/qwc2/config-in:/srv/qwc_service/config-in:ro
      - /app/qwc2/config:/srv/qwc_service/config-out
      - /app/qwc2/qwc2:/qwc2
      - /app/qwc2/qgs-resources:/data
      - /app/qwc2/pg_services:/srv/pg_services:ro
      - /etc/localtime:/etc/localtime:ro
      # Remplacement du script tenant_handler.py pour prendre en compte le tenant dans le sous-domaine
      - /app/qwc2/source_code/qwc-service-core/tenant_handler.py:/usr/lib/python3.9/site-packages/qwc_services_core/tenant_handler.py

  qwc-ogc-service:
    image: sourcepole/qwc-ogc-service:v2022.08.22
    environment:
      <<: *qwc-service-variables
      SERVICE_MOUNTPOINT: '/ows'
    volumes:
      - /app/qwc2/config:/srv/qwc_service/config:ro
      - /etc/localtime:/etc/localtime:ro
      # Remplacement du script tenant_handler.py pour prendre en compte le tenant dans le sous-domaine
      - /app/qwc2/source_code/qwc-service-core/tenant_handler.py:/usr/lib/python3.9/site-packages/qwc_services_core/tenant_handler.
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.r_qwc2_ogc.rule=Host(`${QWC2_HOST}`) && PathPrefix(`/ows`)"
      #- "traefik.http.routers.r_qwc2_ogc.entrypoints=websecure"
      - "traefik.http.routers.r_qwc2_ogc.entrypoints=web"
      - "traefik.http.services.s_qwc2_ogc.loadbalancer.server.port=9090"
      - "traefik.http.routers.r_qwc2_ogc.service=s_qwc2_ogc"

  qwc-data-service:
    image: sourcepole/qwc-data-service:v2022.08.22
    environment:
      <<: *qwc-service-variables
      SERVICE_MOUNTPOINT: '/api/v1/data'
      ATTACHMENTS_BASE_DIR: '/attachments'
      MAX_ATTACHMENT_FILE_SIZE: 1048576
    volumes:
      - /app/qwc2/pg_services:/srv/pg_services:ro
      - /app/qwc2/config:/srv/qwc_service/config:ro
      - /app/qwc2/attachments:/attachments
      - /etc/localtime:/etc/localtime:ro
      # Remplacement du script tenant_handler.py pour prendre en compte le tenant dans le sous-domaine
      - /app/qwc2/source_code/qwc-service-core/tenant_handler.py:/usr/lib/python3.9/site-packages/qwc_services_core/tenant_handler.
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.r_qwc2_data.rule=Host(`${QWC2_HOST}`) && PathPrefix(`/api/v1/data`)"
      #- "traefik.http.routers.r_qwc2_data.entrypoints=websecure"
      - "traefik.http.routers.r_qwc2_data.entrypoints=web"
      - "traefik.http.services.s_qwc2_data.loadbalancer.server.port=9090"
      - "traefik.http.routers.r_qwc2_data.service=s_qwc2_data"

  qwc-solr:
    image: solr:8.11.1-slim
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - gdi
      - /gdi_conf
    # ports:
     # - "127.0.0.1:8983:8983"
    volumes:
      - /app/qwc2/solr/configsets/gdi:/gdi_conf:ro
      # Configuration is copied once from /gdi_conf/ to /var/solr/data/
      # Change ownership to solr user with `sudo chown 8983:8983 volumes/solr/data`
      #- /app/qwc2/solr/data:/var/solr/data
      # Protect admin GUI and admin API with Basic auth
      # Change "#credentials" to "credentials" in security.json for adding a user 'solr' with password 'SolrRocks'
      #- ./volumes/solr/security.json:/var/solr/data/security.json:ro
      - /etc/localtime:/etc/localtime:ro

  qwc-fulltext-search-service:
    image: sourcepole/qwc-fulltext-search-service:v2022.08.22
    environment:
      <<: *qwc-service-variables
      SERVICE_MOUNTPOINT: '/api/v2/search'
    volumes:
      - /app/qwc2/pg_services:/srv/pg_services:ro
      - /app/qwc2/config:/srv/qwc_service/config:ro
      - /etc/localtime:/etc/localtime:ro
      # Remplacement du script tenant_handler.py pour prendre en compte le tenant dans le sous-domaine
      - /app/qwc2/source_code/qwc-service-core/tenant_handler.py:/usr/lib/python3.9/site-packages/qwc_services_core/tenant_handler.
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.r_qwc2_search.rule=Host(`${QWC2_HOST}`) && PathPrefix(`/api/v2/search`)"
      #- "traefik.http.routers.r_qwc2_search.entrypoints=websecure"
      - "traefik.http.routers.r_qwc2_search.entrypoints=web"
      - "traefik.http.services.s_qwc2_search.loadbalancer.server.port=9090"
      - "traefik.http.routers.r_qwc2_search.service=s_qwc2_search"

  qwc-map-viewer:
    image: sourcepole/qwc-map-viewer-demo:v2022.08.25
    # Update config.json with:
    # curl -o volumes/config-in/config.json https://github.com/qgis/qwc2-demo-app/raw/v2022.01.08/static/config.json
    # and generate service configuration
    # With custom build added via volume:
    # image: sourcepole/qwc-map-viewer-base:v2022.08.25
    environment:
      <<: *qwc-service-variables
      SERVICE_MOUNTPOINT: '/'
    volumes:
      - /app/qwc2/pg_services:/srv/pg_services:ro
      - /app/qwc2/config:/srv/qwc_service/config:ro
      # When using qwc-map-viewer-demo:
      - /app/qwc2/qwc2/assets:/qwc2/assets:ro
      # When using own viewer build with qwc-map-viewer-base:
      #- /app/qwc2/qwc2:/qwc2:ro
      - /etc/localtime:/etc/localtime:ro
      # Remplacement du script tenant_handler.py pour prendre en compte le tenant dans le sous-domaine
      - /app/qwc2/source_code/qwc-service-core/tenant_handler.py:/usr/lib/python3.9/site-packages/qwc_services_core/tenant_handler.
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.r_qwc2_map.rule=Host(`${QWC2_HOST}`)"
      #- "traefik.http.routers.r_qwc2_map.entrypoints=websecure"
      - "traefik.http.routers.r_qwc2_map.entrypoints=web"
      - "traefik.http.services.s_qwc2_map.loadbalancer.server.port=9090"
      - "traefik.http.routers.r_qwc2_map.service=s_qwc2_map"

  qwc-admin-gui:
    image: sourcepole/qwc-admin-gui:v2022.08.19
    environment:
      <<: *qwc-service-variables
      # Don't enable JWT CSRF protection for admin gui, it conflicts with CSRF protection offered by Flask-WTF
      JWT_COOKIE_CSRF_PROTECT: 'False'
      USER_INFO_FIELDS: '[{"title": "Surname", "name": "surname", "type": "text", "required": true}, {"title": "First name", "name": "first_name", "type": "text", "required": true}, {"title": "Street", "name": "street", "type": "text"}, {"title": "ZIP", "name": "zip", "type": "text"}, {"title": "City", "name": "city", "type": "text"}]'
      #TOTP_ENABLED: 'False'
      GROUP_REGISTRATION_ENABLED: 'True'
      IDLE_TIMEOUT: 600
      DEFAULT_LOCALE: 'en'
      MAIL_SUPPRESS_SEND: 'True'
      MAIL_DEFAULT_SENDER: 'from@example.com'
    volumes:
      - /app/qwc2/pg_services:/srv/pg_services:ro
      - /app/qwc2/config:/srv/qwc_service/config:ro
      - /etc/localtime:/etc/localtime:ro
      # Volumes for plugins
      - /app/qwc2/qwc2:/qwc2:ro
      - /app/qwc2/qgs-resources:/data
      - /app/qwc2/config-in:/srv/qwc_service/config-in
      # Remplacement du script tenant_handler.py pour prendre en compte le tenant dans le sous-domaine
      - /app/qwc2/source_code/qwc-service-core/tenant_handler.py:/usr/lib/python3.9/site-packages/qwc_services_core/tenant_handler.
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.r_qwc2_admin.rule=Host(`${QWC2_HOST}`) && PathPrefix(`/qwc_admin`)"
      #- "traefik.http.routers.r_qwc2_admin.entrypoints=websecure"
      - "traefik.http.routers.r_qwc2_admin.entrypoints=web"
      - "traefik.http.services.s_qwc2_admin.loadbalancer.server.port=9090"
      - "traefik.http.routers.r_qwc2_admin.service=s_qwc2_admin"

  # qwc-auth-service:
  #   image: sourcepole/qwc-db-auth:v2022.08.22
  #   environment:
  #     <<: *qwc-service-variables
  #     SERVICE_MOUNTPOINT: '/auth'
  #     # https://flask-jwt-extended.readthedocs.io/en/stable/options/#cookie-options
  #     JWT_COOKIE_SAMESITE: 'Strict'
  #     # Enable the following in production (requires https):
  #     #JWT_COOKIE_SECURE: 'True'
  #     #TOTP_ENABLED: 'False'
  #     #TOTP_ISSUER_NAME: 'QWC Services'
  #     MAIL_SUPPRESS_SEND: 'True'
  #     MAIL_DEFAULT_SENDER: 'from@example.com'
  #   volumes:
  #     - pg_services:/srv/pg_services:ro
  #     - config:/srv/qwc_service/config:ro
  #     - /etc/localtime:/etc/localtime:ro
  #     # Remplacement du script tenant_handler.py pour prendre en compte le tenant dans le sous-domaine
  #     - /app/qwc2/source_code/qwc-service-core/tenant_handler.py:/usr/lib/python3.9/site-packages/qwc_services_core/tenant_handler.
      
  qwc-auth-service:
    image: sourcepole/qwc-ldap-auth:v2022.08.22
    environment:
      <<: *qwc-service-variables
      SERVICE_MOUNTPOINT: '/auth'
      JWT_COOKIE_SAMESITE: 'Strict'
      LDAP_HOST: ${LDAP_HOST}
      LDAP_PORT: 389
      LDAP_USE_SSL: False
      LDAP_BASE_DN: ${LDAP_BASE_DN}
      LDAP_USER_DN: 'ou=agents'
      LDAP_GROUP_DN: 'ou=groupes'
      LDAP_SEARCH_FOR_GROUPS: True
      LDAP_GROUP_OBJECT_FILTER: '(objectClass=groupOfUniqueNames)'
      LDAP_GROUP_SEARCH_SCOPE: 'SUBTREE'
      LDAP_USER_LOGIN_ATTR: 'uid'
      LDAP_BIND_USER_DN: ${LDAP_BIND_USER_DN}
      LDAP_BIND_USER_PASSWORD: ${LDAP_BIND_USER_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # Remplacement du script tenant_handler.py pour prendre en compte le tenant dans le sous-domaine
      - /app/qwc2/source_code/qwc-service-core/tenant_handler.py:/usr/lib/python3.9/site-packages/qwc_services_core/tenant_handler.
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.r_qwc2_auth.rule=Host(`${QWC2_HOST}`) && PathPrefix(`/auth/`)"
      #- "traefik.http.routers.r_qwc2_auth.entrypoints=websecure"
      - "traefik.http.routers.r_qwc2_auth.entrypoints=web"
      - "traefik.http.services.s_qwc2_auth.loadbalancer.server.port=9090"
      - "traefik.http.routers.r_qwc2_auth.service=s_qwc2_auth"

  qwc-elevation-service:
    image: sourcepole/qwc-elevation-service:v2022.08.22
    environment:
      <<: *qwc-service-variables
      SERVICE_MOUNTPOINT: '/elevation'
    volumes:
      - /app/qwc2/config:/srv/qwc_service/config:ro
      - /etc/localtime:/etc/localtime:ro
      # Remplacement du script tenant_handler.py pour prendre en compte le tenant dans le sous-domaine
      - /app/qwc2/source_code/qwc-service-core/tenant_handler.py:/usr/lib/python3.9/site-packages/qwc_services_core/tenant_handler.
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.r_qwc2_elevation.rule=Host(`${QWC2_HOST}`) && PathPrefix(`/elevation`)"
      #- "traefik.http.routers.r_qwc2_elevation.entrypoints=websecure"
      - "traefik.http.routers.r_qwc2_elevation.entrypoints=web"
      - "traefik.http.services.s_qwc2_elevation.loadbalancer.server.port=9090"
      - "traefik.http.routers.r_qwc2_elevation.service=s_qwc2_elevation"

  qwc-permalink-service:
    image: sourcepole/qwc-permalink-service:v2022.08.22
    environment:
      <<: *qwc-service-variables
      SERVICE_MOUNTPOINT: '/api/v1/permalink'
    volumes:
      - /app/qwc2/pg_services:/srv/pg_services:ro
      - /app/qwc2/config:/srv/qwc_service/config:ro
      - /etc/localtime:/etc/localtime:ro
      # Remplacement du script tenant_handler.py pour prendre en compte le tenant dans le sous-domaine
      - /app/qwc2/source_code/qwc-service-core/tenant_handler.py:/usr/lib/python3.9/site-packages/qwc_services_core/tenant_handler.
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.r_qwc2_permalink.rule=Host(`${QWC2_HOST}`) && PathPrefix(`/api/v1/permalink`)"
      #- "traefik.http.routers.r_qwc2_permalink.entrypoints=websecure"
      - "traefik.http.routers.r_qwc2_permalink.entrypoints=web"
      - "traefik.http.services.s_qwc2_permalink.loadbalancer.server.port=9090"
      - "traefik.http.routers.r_qwc2_permalink.service=s_qwc2_permalink"

  qwc-print-service:
    image: sourcepole/qwc-print-service:v2022.08.22
    environment:
      <<: *qwc-service-variables
      SERVICE_MOUNTPOINT: '/api/v1/print'
    volumes:
      - /app/qwc2/config:/srv/qwc_service/config:ro
      - /etc/localtime:/etc/localtime:ro
      # Remplacement du script tenant_handler.py pour prendre en compte le tenant dans le sous-domaine
      - /app/qwc2/source_code/qwc-service-core/tenant_handler.py:/usr/lib/python3.9/site-packages/qwc_services_core/tenant_handler.
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.r_qwc2_print.rule=Host(`${QWC2_HOST}`) && PathPrefix(`/api/v1/print`)"
      #- "traefik.http.routers.r_qwc2_print.entrypoints=websecure"
      - "traefik.http.routers.r_qwc2_print.entrypoints=web"
      - "traefik.http.services.s_qwc2_print.loadbalancer.server.port=9090"
      - "traefik.http.routers.r_qwc2_print.service=s_qwc2_print"

  qwc-feature-info-service:
    image: sourcepole/qwc-feature-info-service:v2022.08.22
    environment:
      <<: *qwc-service-variables
      SERVICE_MOUNTPOINT: '/api/v1/featureinfo'
      # SKIP_EMPTY_ATTRIBUTES: 1
    volumes:
      - /app/qwc2/pg_services:/srv/pg_services:ro
      - /app/qwc2/config:/srv/qwc_service/config:ro
      - /etc/localtime:/etc/localtime:ro
      # Remplacement du script tenant_handler.py pour prendre en compte le tenant dans le sous-domaine
      - /app/qwc2/source_code/qwc-service-core/tenant_handler.py:/usr/lib/python3.9/site-packages/qwc_services_core/tenant_handler.
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.r_qwc2_f_info.rule=Host(`${QWC2_HOST}`) && PathPrefix(`/api/v1/featureinfo`)"
      #- "traefik.http.routers.r_qwc2_f_info.entrypoints=websecure"
      - "traefik.http.routers.r_qwc2_f_info.entrypoints=web"
      - "traefik.http.services.s_qwc2_f_info.loadbalancer.server.port=9090"
      - "traefik.http.routers.r_qwc2_f_info.service=s_qwc2_f_info"

  qwc-mapinfo-service:
    image: sourcepole/qwc-mapinfo-service:v2022.08.22
    environment:
      <<: *qwc-service-variables
      SERVICE_MOUNTPOINT: '/api/v1/mapinfo'
    volumes:
      - /app/qwc2/pg_services:/srv/pg_services:ro
      - /app/qwc2/config:/srv/qwc_service/config:ro
      - /etc/localtime:/etc/localtime:ro
      # Remplacement du script tenant_handler.py pour prendre en compte le tenant dans le sous-domaine
      - /app/qwc2/source_code/qwc-service-core/tenant_handler.py:/usr/lib/python3.9/site-packages/qwc_services_core/tenant_handler.
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.r_qwc2_m_info.rule=Host(`${QWC2_HOST}`) && PathPrefix(`/api/v1/mapinfo`)"
      #- "traefik.http.routers.r_qwc2_m_info.entrypoints=websecure"
      - "traefik.http.routers.r_qwc2_m_info.entrypoints=web"
      - "traefik.http.services.s_qwc2_m_info.loadbalancer.server.port=9090"
      - "traefik.http.routers.r_qwc2_m_info.service=s_qwc2_m_info"

  qwc-legend-service:
    image: sourcepole/qwc-legend-service:v2022.08.22
    environment:
      <<: *qwc-service-variables
      SERVICE_MOUNTPOINT: '/api/v1/legend'
    volumes:
      - /app/qwc2/config:/srv/qwc_service/config:ro
      - /app/qwc2/legends:/legends
      - /etc/localtime:/etc/localtime:ro
      # Remplacement du script tenant_handler.py pour prendre en compte le tenant dans le sous-domaine
      - /app/qwc2/source_code/qwc-service-core/tenant_handler.py:/usr/lib/python3.9/site-packages/qwc_services_core/tenant_handler.
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.r_qwc2_legend.rule=Host(`${QWC2_HOST}`) && PathPrefix(`/api/v1/legend`)"
      #- "traefik.http.routers.r_qwc2_legend.entrypoints=websecure"
      - "traefik.http.routers.r_qwc2_legend.entrypoints=web"
      - "traefik.http.services.s_qwc2_legend.loadbalancer.server.port=9090"
      - "traefik.http.routers.r_qwc2_legend.service=s_qwc2_legend"
      
  qwc-project-publisher:
    image: registry.niaubin.fr/qwc-project-publisher
    environment:
      <<: *qwc-service-variables
      AUTH_REQUIRED: True
      SERVICE_MOUNTPOINT: '/publisher'
    volumes:
      - /app/qwc2/config:/srv/qwc_service/config:ro
      - /app/qwc2/qgs-resources:/data
      - /app/qwc2/pg_services:/srv/pg_services:ro
      - /etc/localtime:/etc/localtime:ro
      # Remplacement du script tenant_handler.py pour prendre en compte le tenant dans le sous-domaine
      - /app/qwc2/source_code/qwc-service-core/tenant_handler.py:/usr/lib/python3.9/site-packages/qwc_services_core/tenant_handler.
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.r_qwc2_proj_publisher.rule=Host(`${QWC2_HOST}`) && PathPrefix(`/publisher`)"
      #- "traefik.http.routers.r_qwc2_proj_publisher.entrypoints=websecure"
      - "traefik.http.services.s_qwc2_proj_publisher.loadbalancer.server.port=9090"
      - "traefik.http.routers.r_qwc2_proj_publisher.entrypoints=web"
      - "traefik.http.routers.r_qwc2_proj_publisher.service=s_qwc2_proj_publisher"
      
  qgis-plugins-repository:
    image: registry.niaubin.fr/simple-qgisplugins-repo
    environment:
      MOUNTPOINT: "/plugins/"
    volumes:
      - /app/qgis-plugins/plugins:/app/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.r_qgis_plugins.rule=Host(`${QGIS_PLUGIN_HOST}`)"
      #- "traefik.http.routers.r_qgis_plugins.entrypoints=websecure"
      - "traefik.http.services.s_qgis_plugins.loadbalancer.server.port=80"
      - "traefik.http.routers.r_qgis_plugins.entrypoints=web"
      - "traefik.http.routers.r_qgis_plugins.service=s_qgis_plugins"

networks:
  default:
    name: sig-net
    external: true
