version: '3.4'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    volumes:
      - /${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock
      - ~/.local/share/docker/volumes:/var/lib/docker/volumes
      - portainer_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.r_portainer.rule=Host(`geoportainer.lesagencesdeleau.eu`) || Host(`geoportainer-int.lesagencesdeleau.eu`) || Host(`geoportainer-dev.lesagencesdeleau.eu`)"
      #- "traefik.http.routers.r_portainer.entrypoints=websecure"
      - "traefik.http.routers.r_portainer.entrypoints=web"
      - "traefik.http.services.s_portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.r_portainer.service=s_portainer"
      #- "traefik.http.routers.r_portainer.tls.certresolver=leresolver"

volumes:
  portainer_data: